import self1 from '../img/self1.png'
import self2 from '../img/self2.jpg'
import self3 from '../img/self3.jpg'
import self from '../img/self.jpg'
import mock1 from '../img/mock1.png'
import mock2 from '../img/mock2.png'
import mock3 from '../img/mock3.png'
import mock4 from '../img/mock4.png'
import mock5 from '../img/mock5.png'

/* Hi there! Thanks for checking out my portfolio template. Be sure to read the comments to get a better understanding of
how to make this template work best for you! */

export let colors = ['rgb(0,255,164)', 'rgb(166,104,255)']
/*
I highly recommend using a gradient generator like https://gradientgenerator.paytonpierce.dev/ to generate a pair of colors that you like.
These colors will be used to style your name on the homepage, the background of your picture, and some other accents throughout
the site.
 */

/*
So let's get started! Some of the info below is pretty self-explanatory, like 'firstName' and 'bio'. I'll try to explain anything
that might not be obvious right off the bat :) I recommend looking at the template example live using "npm start" to get an idea
of what each of the values mean.
 */

export const info = {
  firstName: 'Savindu',
  lastName: 'Pasintha',
  initials: '*', //'React+Js+Java+C# ..', // the example uses first and last, but feel free to use three or more if you like.
  positionTop: 'Fullsatck / Frontend Engineering',
  position: 'Software Developer',
  subPosition: ' web/mobile',
  selfPortrait: self1, // don't change this unless you want to name your self-portrait in the "img" folder something else!
  gradient: `-webkit-linear-gradient(135deg, ${colors})`, // don't change this either
  baseColor: colors[0],
  miniBio: [
    // these are just some "tidbits" about yourself. You can look at mine https://paytonjewell.github.io/#/ for an example if you'd like
    {
      emoji: '🌎',
      text: 'Finding a Job',
    },
    {
      emoji: '💼',
      text: '+ 4 Year Experience',
    },

    {
      emoji: '☕',
      text: 'fueled by coffee',
    },
    {
      emoji: '📧',
      text: (
        <a href="mailto:savindupasingtha@gmail.com">
          savindupasingtha@gmail.com / +94 76 875 57 87
        </a>
      ),
    },
  ],
  socials: [
    {
      link: 'https://www.linkedin.com/in/savindu-pasintha/',
      icon: 'fa fa-linkedin',
      label: 'linkedin',
    },
    {
      link: 'https://github.com/savindu-pasintha',
      icon: 'fa fa-github',
      label: 'github',
      count: '122',
    },
    {
      link: 'https://savindupasingtha.medium.com',
      icon: 'fa fa-medium',
      label: 'medium',
    },
    {
      link: 'https://stackoverflow.com/users/15484152/savindu-pasintha',
      icon: 'fa fa-stack-overflow',
      label: 'stackpverflow',
    },

    /* {
      link: 'https://facebook.com',
      icon: 'fa fa-facebook',
      label: 'facebook',
    },
    {
      link: 'https://instagram.com',
      icon: 'fa fa-instagram',
      label: 'instagram',
    },

    {
      link: 'https://twitter.com',
      icon: 'fa fa-twitter',
      label: 'twitter',
    },
    */
    // Feel free to remove any of these that you don't have. I'll write an FAQ on how to add new ones later, let me know if you have a request for an icon!
    // Just change the links so that they lead to your social profiles.
  ],
  bio:
    "I'm Savindu Pasintha. I studied at Computing and Software Engineering at Cardiff Metropolitan, University, Uk. Previously,  4.5 years back I worked as a self thought software developer with Multiple orgarnizations, So I have great experience about the software development and maintanances with multiple areas and I am Good team player including with multiple tech stacks.",
  skills: {
    coding: [
      '🌱 JavaScript',
      '🌱 Typescript',
      '🌱 Java',
      '🌱 C#',
      ' 🌱 C++',
      '🌱 Dart',
      '🌱 Kotlin ',
      '🌱 PHP',
      '🌱 Python',
      '🌱 Go',
      '🌱 Solidity',
    ],
    backend: [
      'NodeJs',
      'Express',
      'Springboot',
      '.Net Core',
      'Django',
      'Go',
      'GraphQL',
      ' Elastic Search',
      'Socket.io ',
      'Web-Sockets',
      'REST API Integration',
      'JWT',
      'OAuth',
      'OpenID',
    ],
    frontend: [
      'Reactjs',
      'Angular',
      ' Nextjs',
      ' Vuejs',
      ' Electronjs',
      ' Qt',
      'Micro-Frontend ',
      'Figma-UI',
      'Adobe-UI',
      'HTML',
      'CSS',
      'SCSS',
      'Bootstrap',
      'JQuery',
      'Material-Design',
      'Ant-Design',
      'WordPress',
      'SEO',
      'Block-Chain',
      'Cripto',
      'web3',
      'Metamask',
    ],
    mobile: ['Android', 'Java', 'Kotlin', 'React-Native', 'Dart', 'Flutter'],
    desktop: ['C++ QT Framework', 'C# .NET Framework', 'Java '],
    database: ['SQL', 'MySql', 'SqlLite', 'MongoDB', 'Firebase ', 'Nosql'],
    cloud: ['AWS', 'AZURE', 'Google Cloud'],
    proficientWith: [
      'javascript',
      'react',
      'git',
      'github',
      'bootstrap',
      'html5',
      'css3',
      'figma',
    ],
    exposedTo: ['nodejs', 'python', 'adobe illustrator'],
  },
  hobbies: [
    {
      label: 'programing',
      emoji: '📖',
    },
    {
      label: 'researching new technologies',
      emoji: '🎭',
    },
    {
      label: 'self learning',
      emoji: '🎥',
    },
    {
      label: 'designing',
      emoji: '🌶',
    },
    {
      label: 'traveling',
      emoji: '🎭',
    },
    {
      label: 'freedom',
      emoji: '🎥',
    },
    {
      label: 'cooking',
      emoji: '🌶',
    },
    // Same as above, change the emojis to match / relate to your hobbies or interests.
    // You can also remove the emojis if you'd like, I just think they look cute :P
  ],
  education: [
    {
      id: 1,
      what: 'BSC(Hons) Computing & Software Engineering',
      where: 'Cardiff Metropolitan, University, Uk',
      time: ' 2019',
      grade: "1'st Class",
    },
    {
      id: 2,
      what: 'Higher National Diploma in Computing & Software Engineering',
      where: 'International College Of Business & Technology, Sri Lanka',
      time: ' 2019',
      grade: "1'st Class",
    },
    {
      id: 3,
      what: 'Certificate In Computer Hardware & Network',
      where:
        'Foundation of Goodness OYOB Centre of Excellence, Sinigama , Sri Lanka',
      time: 'Jan 2019 - July 2019 ',
      grade: '',
    },
    {
      id: 4,
      what: 'High School (GCE Advanced Level(GCE A/L))',
      where: 'National School, Ananada Sastralaya, Mathugama, Sri Lanaka',
      time: '2015 - August 2018',
      grade: `Physical Science Stream  (Physics/Combine Maths/Chemistry)`,
    },
    {
      id: 5,
      what: 'Primary School (GCE Ordinary Level(GCE O/L))',
      where: 'National School, Ananada Sastralaya, Mathugama, Sri Lanaka',
      time: '2010 - 2015',
      grade: `8A & 1B`,
    },
  ],
  workHistory: [
    {
      id: 1,
      role: 'Software Engineer',
      company: 'X.O CONCEPTS (PRIVATE) LIMITED',
      location: 'No 30/81- 1/1 ,Longdon Place , Colombo 07 , Sri Lanka.',
      time: '',
      summery:
        'React Multifunctional Dashboard & Desktop Applications Development using ReactJs / Node Js / Go / C++ / QT Framework / AWS / Micro services / Material / Html / CSS / Bosstrap / Style Components /Mysql / REST API / Python / Machine Learning / IOT Devices /git lab / git bucket..',
    },
    {
      id: 2,
      role: 'Software Developer (Remote)',
      company: 'Natobotics Technologies Pvt Ltd.',
      location:
        '#1206, 12th Floor, D-South Block, Tidel Park, Rajiv Gandhi Salai, Taramani, Chennai 600 113, india',
      time: '',
      summery:
        'React Multifunctional Dashboard Development / Static Web sites /REST API / ReactJS Framework / Javascript / Typescript /Html / CSS / Boostrap /ANT Design / Material Design / Mysql / MondoDB / Azure / Clould / C# / .Net Framework / .Net core api / Python / Webscraping /github / git lab',
    },
    {
      id: 3,
      role: 'Associate Software Engineer',
      company: 'Nvision IT Solutions (PVT) Limited',
      location: '10 Kumarage Watta Road, Sri Jayawardenepura Kotte,Sri Lanka',
      time: '',
      summery:
        'Mobile applications development and Web applications development with Java / React Native / Flutter /git lab / git hub /Rest Services /Sqlite database / Mysql /Jet pack /room database / AWS ',
    },
    {
      id: 4,
      role: 'Associate DevOPS Engineer',
      company: 'Global Wavenet International Pvt Ltd , Singappore',
      time: '2019',
      location: '',
      summery:
        'USSD & IVR(Interact voice response) Systems Development AWS / NodeJs / Javascript / kapanga Tool / System Design / Machine Learning / gitbucket ',
    },
    {
      id: 1,
      role: 'Software Developer',
      company: 'Upwork.com & Fiver.com',
      location: '',
      time: '',
      summery:
        'Full stack web & mobile applications development & Mobile app reverse engineering',
    },
  ],
  portfolio: [
    // This is where your portfolio projects will be detailed
    {
      id: 3,
      title:
        'ReactJs Multi Functional Dashboard  (Veritas Petroleum Services USA)',
      summery:
        'This site mainly used for the USA Petroleum Company to manage their all the task',
      technologies: [
        'javascript',
        '@material-ui/core',
        'axios',
        'typescrite',
        'mui-datatables',
        'mathjax-react',
        'material-tabs',
        'react-pdf',
        'react-google-charts',
        'chart.js',
        'js-file-downloader',
        'react-equation',
        'react-date-range',
        'git',
        'redux',
        'react-pro-sidebar',
        'react-redux',
        'react-resizable',

        'react-tinder-card',
        'react-simple-maps',
        'react-select-async-paginate',
        'react-select',
        'react-image-gallery',
      ],
      usedModules: [
        'canvasjs',
        'atob',
        'qrcode.react',
        'AWS',
        'react-blink-text',
        'html5',
        'react-bootstrap-table-next',
        'figma',
        'mathjax-react',
        '@date-io/moment',
        '@fortawesome/react-fontawesome',
        'bootstrap',
        'html5',
        'css3',
        'react-material-ui-carouse',
        'recharts',
        'react-tooltip',
        'react-virtualized',
        'react-toastify',
      ],
      live: '',
      source: '',
      image: mock2,
      imagesUrl: [
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/VPS%20React%20Dashboard%2F3.PNG?alt=media&token=352cf3b5-9c6b-420b-b777-0771db4dc220',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/VPS%20React%20Dashboard%2F1.PNG?alt=media&token=665a614f-bce4-4cff-b1f4-d8ee7732391a',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/VPS%20React%20Dashboard%2F2.PNG?alt=media&token=ed16b02e-09db-46b1-82b0-55dffda76c7a',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/VPS%20React%20Dashboard%2F4.PNG?alt=media&token=52998491-f7a5-4ca9-9064-4471550b445e',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/VPS%20React%20Dashboard%2F5.PNG?alt=media&token=6eef9b0f-09a4-474c-9906-680d294c9521',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/VPS%20React%20Dashboard%2F6.PNG?alt=media&token=fbfc2f4e-06c2-4495-8dab-c8bf610b3043',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/VPS%20React%20Dashboard%2F7.PNG?alt=media&token=e312e47c-0edb-4436-843a-5e45a1bbf6ae',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/VPS%20React%20Dashboard%2F8.PNG?alt=media&token=90bd2bae-e2d1-40a6-80f8-5a053dd7412c',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/VPS%20React%20Dashboard%2F9.PNG?alt=media&token=029110a9-d3ff-4395-abad-ed79de73af7e',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/VPS%20React%20Dashboard%2F10.PNG?alt=media&token=951e02a7-5a5d-414a-a6de-dac4aa73a321',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/VPS%20React%20Dashboard%2F11.PNG?alt=media&token=d5b598ab-2713-4daa-aa4f-b40426a0bfb1',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/VPS%20React%20Dashboard%2F12.PNG?alt=media&token=bc847c8a-cd7d-48c9-bb36-ee46a726e153',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/VPS%20React%20Dashboard%2F13.PNG?alt=media&token=3b3ba687-c3f8-4021-b69f-05aecdcbd485',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/VPS%20React%20Dashboard%2F14.PNG?alt=media&token=85f8c20d-eade-4e66-912b-73de78a2741a',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/VPS%20React%20Dashboard%2F15.PNG?alt=media&token=e0216806-4a56-4f2b-b87d-411b44f06ee5',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/VPS%20React%20Dashboard%2F16.PNG?alt=media&token=b3401a70-53cf-483a-a8f3-4dd0e0ec3461',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/VPS%20React%20Dashboard%2F17.PNG?alt=media&token=148e5bc4-9b2c-467c-891a-011f8ab22b46',
      ],
    },
    {
      id: 1,
      title: 'React Web Application `Beats Health`(for USA)',
      summery:
        'This One is a React Frontend and .NET Backend based on Hospital Management Dashboard.',
      technologies: [
        'react',
        'javascript',
        '@mui/Material Design',
        '@material-ui',
        'axios',
        'REST Service',
        'react-time-picker',
        'react-select',
        'react-phone-input-2',
        'react-toastify',
        'react-modal',
        'material-table',
        'react-collapsible',
        'react-base64-downloader',
        'git',
        'github',
        'bootstrap',
        'html5',
        'css3',
        'figma',
        '.net',
        'c#',
        'Pdf downloads',
      ],
      usedModules: ['date-fns', 'responsive', 'aws sdk', 'sass'],
      live: '', //this should be a link to the live version of your project, think github pages, netlify, heroku, etc. Or your own domain, if you have it.
      source: '', // this should be a link to the **repository** of the project, where the code is hosted.
      image: mock1,
      imagesUrl: [
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/Beats%20Health%20Project%2F1.PNG?alt=media&token=8dcdabfd-cc08-4065-a668-b7d3fc96fd83',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/Beats%20Health%20Project%2F2.PNG?alt=media&token=3ec4c0ca-ad20-4c98-bbf0-acfd5a163d99',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/Beats%20Health%20Project%2F3.PNG?alt=media&token=fc58babf-c406-4f87-bd24-0c41253933af',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/Beats%20Health%20Project%2F4.PNG?alt=media&token=41cd8063-437b-4b95-a2d5-6708af3e4a76',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/Beats%20Health%20Project%2F5.PNG?alt=media&token=77898f88-bb84-49f0-bcf3-dd7579856b35',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/Beats%20Health%20Project%2F6.PNG?alt=media&token=b2a5463d-559d-40b2-9b05-a4afa278b3a9',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/Beats%20Health%20Project%2F7.PNG?alt=media&token=7cd2f811-2052-4c9d-8c49-ea5e4f7a6b29',
      ],
    },
    {
      id: 2,
      title: 'Veritas Petroleum Services Static Web Site (for USA)',
      summery:
        'This Project for Veritas Petroleum Services(vps). They do world wide OIL testing and report generation.',
      technologies: [
        'javascript',
        'Html',
        'Jquery',
        'github',
        'bootstrap',
        'SEO',
        'Pdf downloads',
        'charts',
        'Maps',
      ],
      usedModules: [],
      live: 'https://www.vpsveritas.com',
      source: '',
      image: mock2,
      imagesUrl: [
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/VPS%20Frontend%20web%20site%20html%2F1.PNG?alt=media&token=3c9d13c9-cf95-4253-b492-b3763fbc2e46',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/VPS%20Frontend%20web%20site%20html%2F2.PNG?alt=media&token=504a3384-e448-48a9-95c3-4de6bfb686e2',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/VPS%20Frontend%20web%20site%20html%2F3.PNG?alt=media&token=8482bfa7-c97b-4b90-8c48-760821c12bce',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/VPS%20Frontend%20web%20site%20html%2F4.PNG?alt=media&token=4b3a82ec-4545-4e29-b721-6103e004b5ee',
      ],
    },

    {
      id: 5,
      title:
        'Point of Sale and Inventory Management Software(Mobile  & Web Application)',
      summery:
        'This project for the Android and Web Application for POS system for Nvision (pvt) LTD.',
      technologies: [
        'Android',
        'facebook login',
        'play service authentication(GSM)',
        'web view',
        'Android networking',
        'Material Design',
        'Dashboard Management',
        'Payment Gateways ',
        'Multi Role Authentication',
        'Jetpack',
        'API',
        'REST Services',
        'Multi language Support',
        'MySql Database',
        'AWS',
        'clould',
        'Retrofit',
        'Google map',
        'firebase firestore realtime datatbase analytics',
        'Junit',
        'Animation',
        'Room Database',
        'SQLite',
        'JSon',
        'Country/date time picker',
        'js out',
        'Google Play Store',
        'coil image',
        'pdf download',
        'scroller view',
      ],
      usedModules: ['Web site', 'php', 'html', 'css', 'boostrap', 'jquery'],
      live: 'https://www.salesplay.com',
      source: '',
      image: mock2,
      imagesUrl: [
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/POS%20Nvision%2F1.PNG?alt=media&token=2c665121-c4ea-4d75-8242-417eb99b468e',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/POS%20Nvision%2F2.PNG?alt=media&token=4251e8be-d053-45ba-8aa2-56270570f63d',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/POS%20Nvision%2F3.webp?alt=media&token=9b60201c-5741-4419-af22-8dd5eb1eb277',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/POS%20Nvision%2F4.webp?alt=media&token=61f52594-9cfc-4603-a047-ac80ebfbabda',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/POS%20Nvision%2F5.PNG?alt=media&token=8659463c-e0d6-4316-8f72-ee8c890cac09',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/POS%20Nvision%2F6.webp?alt=media&token=f32b5d61-9625-4a53-9f99-9e3a997f9729',
        ,
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/POS%20Nvision%2F7.webp?alt=media&token=576aaf4d-a330-4ac6-99ce-2f56feb24389',
      ],
    },
    {
      id: 6,
      title: 'React Native - Sales Play Dashboard app',
      summery:
        'Thsi App for the Nvision Lanka pvt LTD to show their products statistics showing app',
      technologies: [
        'React Native',
        'expo',
        'react-native-screens',
        'react-native-tab-view',
        'android',
        'react-native-paper',
        'react-native-pager-view',
        'ios',
        'react-native-check-box',
        'expo-sqlite',
        'expo-status-bar',
        'react-native-gesture-handler',
      ],
      usedModules: ['expo-file-system', '@expo/vector-icons', 'native base'],
      live: '',
      source:
        'https://github.com/savindu-pasintha/react-native-sales-play-dashboard',
      image: mock2,
      imagesUrl: [
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/sales%20play%20pos%20dashboard%20app%2F1.jpg?alt=media&token=bbf00f30-b029-48eb-895a-ff4e4a6fc1d5',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/sales%20play%20pos%20dashboard%20app%2F2.jpg?alt=media&token=bc67b3c3-b2d3-48dd-88bc-ed6bb4b74547',
      ],
    },
    {
      id: 6,
      title: 'Android Java Ecommerce App (Cup Cake selling)',
      summery:
        'This Android mobile app for selling cupcakes, special occasion cupcakes and all kind of sweets. And also they offer cupcake decoration classes also. It can manage client orders, manage stock and many other benefits included.',
      technologies: [
        'Java',
        'payment gateway',
        'Android',
        'room databse',
        'SqlLite',
        'API Handling',
        'Material Design',
        'Firebase Authetication',
      ],
      usedModules: [
        'com.google.android.material:material',
        'androidx.constraintlayout:constraintlayout',
        'junit',
        'com.github.bumptech.glide:glide',
      ],
      live: '',
      source:
        'https://github.com/savindu-pasintha/Java-cupCakes-app-ecommerce/tree/main/cupcakeapp',
      image: mock2,
      imagesUrl: [
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/cupcake%20app%20java%20android%2F5.PNG?alt=media&token=c506d727-cf6d-4c2d-a9d0-290612a72a62',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/cupcake%20app%20java%20android%2F1.PNG?alt=media&token=7c443ab5-de1a-4298-ab51-e3ae0c01ef14',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/cupcake%20app%20java%20android%2F2.PNG?alt=media&token=5fe14a54-1a5e-4153-927b-ddae9792edc8',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/cupcake%20app%20java%20android%2F3.PNG?alt=media&token=7de29bfb-fa5f-404c-8eee-a69af227cb07',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/cupcake%20app%20java%20android%2F4.PNG?alt=media&token=17f95094-0e19-4969-8066-9d5f286cbd6f',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/cupcake%20app%20java%20android%2F6.PNG?alt=media&token=27ead611-6893-4b27-86de-6f1938a5ec72',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/cupcake%20app%20java%20android%2F7.PNG?alt=media&token=234423e3-83fc-462b-9823-1050892fef84',
      ],
    },
    {
      id: 6,
      title: 'Android Java `News App`',
      summery:
        'This app based on the java native Android app development. Anyone Can News search and show the all the details about that topic.I used Retrofit library with singleton design pattern for the `newsapi.org` API data access.',

      technologies: [
        'Java',
        'com.squareup.retrofit2:retrofit',
        'Android',
        'swiperefreshlayout:swiperefreshlayout',
        'Android web view',
        'Android Networking',
        'com.google.android.gms:play-services-ads',
        'Singleton pattern',
        'Retrofit Https Request handling',
        'org.ocpsoft.prettytime:prettytime',
        'Android Material Design',
        'com.squareup.retrofit2:converter-gson',
      ],
      usedModules: [
        'News Searching',
        'io.github.medyo:android-about-page',
        'Show Vidios',
        'Show Images',
        'com.squareup.picasso:picasso',
        'commenting',
      ],
      live:
        'https://github.com/savindu-pasintha/Android-Java-news-app/tree/master/app/release',
      source: 'https://github.com/savindu-pasintha/Android-Java-news-app',
      image: mock2,
      imagesUrl: [
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/Android%20News%20app%20java%2F2.jpg?alt=media&token=bd6d0de0-defa-4641-85c8-7d968c719c34',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/Android%20News%20app%20java%2F3.jpg?alt=media&token=25ed25f5-82ad-435f-a134-c14c2d7dfa35',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/Android%20News%20app%20java%2F4.jpg?alt=media&token=8f1c2ce0-1747-4768-9f35-5af4c1d89b6f',

        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/Android%20News%20app%20java%2F1.jpg?alt=media&token=f677ed5a-4f08-4320-b39c-dc9769c69c33',
      ],
    },
    {
      id: 6,
      title: 'Android Java `Wallpaper changing App`',
      summery:
        'Users can see multiple wallpapers in the screen. when user select one wallpaper he/she can  set as a mobile Lock screen and Home screen wallpaper',
      technologies: [
        'Java',
        'Android',
        'Jet pack',
        'Image hangling',
        'android.material',
        'internet',
        'android.gms:play-services-ads',
        'Retrofit API',
        'com.squareup.retrofit2:retrofit:2.4.0',
        'com.squareup.retrofit2:converter-gson:2.2.0',
        'Picaso for image url com.squareup.picasso:picasso:2.5.0',
        'image url set to image view com.github.bumptech.glide:glide:4.12.0',
      ],
      usedModules: ['Change The mobile phone wallpaper'],
      live: '',
      source:
        'https://github.com/savindu-pasintha/Android-APPS-JAVA/tree/master/WallpaperChangeApp',
      image: mock2,
      imagesUrl: [
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/wallpaper%20app%20android%20java%2F1.jpg?alt=media&token=453fe0db-861e-4b24-9a39-7b0ecca059f7',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/wallpaper%20app%20android%20java%2F2.jpg?alt=media&token=b521fbe7-6de5-4d4d-a130-f1560422bdeb',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/wallpaper%20app%20android%20java%2F3.jpg?alt=media&token=1a8253c4-7e6b-4e6e-aaa5-9f8bd6a93867',
      ],
    },
    {
      id: 6,
      title: 'Android Java `Whatsapp Status Saving App`',
      summery:
        'This app user to allow , their whatsapp status saving to Mobile phone file Storage.',
      technologies: [
        'Java',
        'Android',
        'Jet pack',
        'Image hangling',
        'android.material',
        'internet',
        'android.gms:play-services-ads',
        'Retrofit API',
        'com.squareup.retrofit2:retrofit:2.4.0',
        'com.squareup.retrofit2:converter-gson:2.2.0',
        'Picaso for image url com.squareup.picasso:picasso:2.5.0',
        'image url set to image view com.github.bumptech.glide:glide:4.12.0',
      ],
      usedModules: [
        '✔️ View WhatsApp stories',
        '✔️ Save WhatsApp stories',
        '✔️ Full Screen Whatsapp Stories view',
        '✔️ Preview Downloaded Story',
        '✔️ Offers WhatsApp status download option',
        '✔️ Share with Friends',
        '✔️ Delete Unwanted Whatsapp Story',
      ],
      live: '',
      source:
        'https://github.com/savindu-pasintha/Android-APPS-JAVA/tree/master/Status-Saver-master',
      image: mock2,
      imagesUrl: [
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/whatsapp%20status%20saving%20app%2F2.PNG?alt=media&token=281a1f8b-d611-44e0-b108-ac23ca4aa148',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/whatsapp%20status%20saving%20app%2F1.PNG?alt=media&token=d869e112-37b8-4db8-86a3-201325292ad2',
      ],
    },
    {
      id: 6,
      title: 'React Native (Uber Eats Clone App)',
      summery: 'This app for React Native sample `uber eats clone`',
      technologies: [
        'React Native',
        'firebase',
        'firestore',
        'authentication',
        'react-native-elements',
        'react-native-reanimated',
        'redux',
        'react-native-vector-icons',
        'react-native-bouncy-checkbox',
        'expo',
        'react-native-screens',
        'react-native-tab-view',
        'android',
        'react-native-paper',
        'react-native-pager-view',
        'ios',
        'react-native-check-box',
        'expo-sqlite',
        'expo-status-bar',
        'react-native-gesture-handler',
      ],
      usedModules: [
        'product search',
        'authentication',
        'screen navigations',
        'google map',
        'cart',
        'buy',
        'messaging',
      ],
      live: '',
      source: '',
      image: mock2,
      imagesUrl: [
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/uber%20eats%20%20react%20native%20app%2F1.jpg?alt=media&token=46545e19-e9ef-4ab9-abb1-eae4e78394e8',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/uber%20eats%20%20react%20native%20app%2F3.PNG?alt=media&token=16865925-57bf-46e6-b0a7-4fcd695e2f2e',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/uber%20eats%20%20react%20native%20app%2F5.PNG?alt=media&token=6a908e34-74f4-4691-b56d-1938f01372de',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/uber%20eats%20%20react%20native%20app%2F1.jpg?alt=media&token=46545e19-e9ef-4ab9-abb1-eae4e78394e8',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/uber%20eats%20%20react%20native%20app%2F4.PNG?alt=media&token=d8084aad-1dc5-43ce-9db0-3fd5a299f328',
      ],
    },
    {
      id: 6,
      title: 'React JS / Node js Core Ui Dashboard web application',
      summery:
        'This web site for the Dashboard management system with react core Ui. Backend as a used Nodejs.',
      technologies: [
        'props',
        'Nodejs',
        'expressjs',
        'mysql databse',
        'authO2',
        'core ui template',
        'react',
        'javascript',
        '@mui/Material Design',
        '@material-ui',
        'axios',
        'REST Service',
        'react-time-picker',
        'react-select',
        'react-phone-input-2',
        'react-toastify',
        'react-modal',
        'material-table',
        'react-collapsible',
        'react-base64-downloader',
        'git',
        'github',
        'bootstrap',
        'html5',
        'css3',
        'figma',
        '.net',
        'c#',
        'Pdf downloads',
      ],
      usedModules: [
        'analysis charts',
        'diagrams',
        'date-fns',
        'responsive',
        'aws sdk',
        'sass',
      ],

      live: '',
      source: 'https://github.com/savindu-pasintha/vuejs-Core-Ui-Admin-Panel',
      image: mock2,
      imagesUrl: [
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/React%20JS%20Node%20js%20Core%20Ui%20Dashboard%20web%20application%2F1.PNG?alt=media&token=af5ca586-2c09-44b4-b257-111863cbf219',
      ],
    },
    {
      id: 6,
      title: 'Reactjs `Youtube Clone`',
      summery:
        'A web site allow to Watch Youtube vidios through the Google youtube web API',
      technologies: [
        'google developer API',
        'react',
        'axios',
        'bootstrap',
        'http-proxy-middleware',
        'jquery',
        'popper.js',
        'reactjs-media',
      ],
      usedModules: [''],
      live: 'https://youtubesp.netlify.app/',
      source: 'https://github.com/savindu-pasintha/youtubeClone',
      image: mock2,
      imagesUrl: [
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/youtube%20clone%2F2.PNG?alt=media&token=77a7899d-15ff-44ad-904b-d0f87fd86453',
      ],
    },

    {
      id: 6,
      title: 'Thermal-Printing-Software - (USB Supported)',
      summery:
        'Customer to have fully Freedom to Customize Printing Template any of items. \n Who Can For this : Any kind of Thermal Reciept printing solution you want , you can use this. (ex : sales , shop , market , wholesale ..). You Can connect your : Desktop , Laptop ... In the future, I hope to develop this for remote access your Thermal printer. Tested with ESC(POS) Printers. MultiLang Supported.(Stil Testing with Percian Languages)',
      technologies: [
        'ESC(pos) COMMANDS',
        'c# language',
        'C# web sockets',
        '.net framework',
        'Desktop application',
        'thermal printers',
        'pc Hardware access',
        'API hanlding',
        'muti language supporting',
        'html',
        'css',
        'javascript',
      ],
      usedModules: ['data encoding', 'decoding', 'printers access'],
      live:
        'https://github.com/savindu-pasintha/Thermal-Printing-Software-Solution-USB-Supported-/blob/main/README.md',
      source:
        'https://github.com/savindu-pasintha/Thermal-Printing-Software-Solution-USB-Supported-/blob/main/README.md',
      image: mock2,
      imagesUrl: [
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/Thermal%20printer%20c%23%2FDESCRIPTION.PNG?alt=media&token=dfa10043-7978-4058-90c2-8371051167bb',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/Thermal%20printer%20c%23%2FWhatsApp%20Image%202022-08-23%20at%2010.33.00%20AM.jpeg?alt=media&token=43509890-9f01-45ba-8459-d72ebe0f0938',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/Thermal%20printer%20c%23%2Fprint%20image.jpg?alt=media&token=a6f3169e-c8d9-4b06-976c-57177b177d85',
      ],
    },
    {
      id: 6,
      title: 'Cheap Resto` React + Nodejs + Machin Learning + Mysql + GraphQL',
      summery: '',
      technologies: [
        'React Js, react bootstraps and other react materials and components.',
      ],
      usedModules: [
        'Cheap Resto',
        'Finding Restaurant',
        'Artificial Intelligence Based Restaurants Filter/Search',
        'Top Restaurants at near you.',
      ],
      live: '',
      source:
        'https://github.com/savindu-pasintha/Java-EE-Hospital-Project-REST-Mysql-with-Jersey',
      image: mock2,
      imagesUrl: [
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/cheap%20resto%20machine%20learning%2F1.png?alt=media&token=73871172-5c25-4659-97f1-dcfacb5fe3d9',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/cheap%20resto%20machine%20learning%2F2.png?alt=media&token=80f49b2d-0178-4e6a-8b01-02c55bbbdadf',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/cheap%20resto%20machine%20learning%2F3.png?alt=media&token=34c31882-d89e-43f6-a2bb-1e0845c4c999',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/cheap%20resto%20machine%20learning%2F4.png?alt=media&token=5e4fdd41-4d4d-4ce7-b648-2c61a49a8563',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/cheap%20resto%20machine%20learning%2F5.png?alt=media&token=2884ff7f-7b78-43f2-a344-90db8061dd8c',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/cheap%20resto%20machine%20learning%2F6.png?alt=media&token=ff70ac48-7bde-4f3b-881d-bbb934f81a82',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/cheap%20resto%20machine%20learning%2F6.png?alt=media&token=ff70ac48-7bde-4f3b-881d-bbb934f81a82',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/cheap%20resto%20machine%20learning%2FCheapresto%20SAD.drawio%20(1).png?alt=media&token=6f3431b2-f020-48c4-952f-564eb52fc15d',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/cheap%20resto%20machine%20learning%2FER%20Database%20Diagram.jpg?alt=media&token=55af7a38-1229-4973-906f-027ab51755b7',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/cheap%20resto%20machine%20learning%2FRestaurant%20Filtering%20Flow.drawio%20(1).png?alt=media&token=75bc47bb-810c-431f-864e-0980ab1caf88',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/cheap%20resto%20machine%20learning%2FSequence%20for%20Ai%20based%20python%20model.jpg?alt=media&token=581d0de5-0fa6-47c9-a4be-18a5a8b222c4',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/cheap%20resto%20machine%20learning%2FUser%20case%20for%20cheap%20resto.drawio.png?alt=media&token=fb5a7afb-aee3-4196-8471-ac09c70f5008',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/cheap%20resto%20machine%20learning%2Flogin%20flow%20chart.png?alt=media&token=265f8963-5974-495d-b569-c851acd2fd47',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/cheap%20resto%20machine%20learning%2Fsign%20in%20sequence.png?alt=media&token=07e96eb3-9eaf-467b-9cf9-524766859f8a',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/cheap%20resto%20machine%20learning%2Fuser%20registration%20flow%20chart.png?alt=media&token=19fb8717-9b33-44a0-859a-74856b29c262',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/cheap%20resto%20machine%20learning%2Fuser%20registration%20sequence%20diagram.png?alt=media&token=d51498a8-a2aa-446a-87f0-9090755c6dbc',
      ],
    },
    {
      id: 6,
      title: '`Whiteboard Application + Audio + vidio`',
      summery:
        'This web application allows to AWS hosting with janus webRTC Canvas Whiteboard sharing Iearning site for one to one education .',
      technologies: [
        'React',
        'Nodejs',
        'socket.io',
        'websocket',
        'canvas sharing',
        'one to one voice/vidio sharing',
        'janus API',
        'enginX',
        'aws',
        'firebase',
      ],
      usedModules: [''],
      live: '',
      source: '',
      image: mock2,
      imagesUrl: [
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/whiteboard%20share%20application%2FWhatsApp%20Image%202022-08-25%20at%206.05.38%20AM%20(1).jpeg?alt=media&token=b4666b53-0f93-4575-a716-1c6468334b38',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/whiteboard%20share%20application%2FWhatsApp%20Image%202022-08-25%20at%206.05.38%20AM%20(1).jpeg?alt=media&token=b4666b53-0f93-4575-a716-1c6468334b38y',
      ],
    },
    {
      id: 6,
      title: 'React Js `You Clever` web site for Developers Hiring',
      summery:
        'This web site look like a stack overflow web site. this web site allow to ad questions or problems, special feature is a automatically generate portfolio profile for all the registered developers. we can download that profile pdf and it we can give as a job interview resume.',
      technologies: [
        'javascript',
        '@material-ui/core',
        'firebase',
        'mysql',
        'axios',
        'typescrite',
        'mui-datatables',
        'mathjax-react',
        'material-tabs',
        'react-pdf',
        'react-google-charts',
        'chart.js',
        'js-file-downloader',
        'react-equation',
        'react-date-range',
        'git',
        'redux',
        'react-pro-sidebar',
        'react-redux',
        'react-resizable',
        'node js backend',
        'react-tinder-card',
        'react-simple-maps',
        'react-select-async-paginate',
        'react-select',
        'react-image-gallery',
      ],
      usedModules: [
        '@material-ui/core',
        'firebase',
        'mysql',
        'axios',
        'typescrite',
        'mui-datatables',
        'mathjax-react',
        'material-tabs',
        'react-pdf',
        'react-google-charts',
        'chart.js',
        'js-file-downloader',
      ],
      live: 'https://youclever.netlify.app/',
      source: 'https://github.com/savindu-pasintha/Youclever-Site-',

      image: mock2,
      imagesUrl: [
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/You%20clever%20site%2F1.png?alt=media&token=5c65604e-f638-496c-9d62-f27f08bb691c',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/You%20clever%20site%2F2.png?alt=media&token=2e4d2a5b-7c96-449a-8b92-13df37630f6f',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/You%20clever%20site%2F3.png?alt=media&token=c095e8aa-2dff-41a7-8971-deabe7550d14',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/You%20clever%20site%2F4.png?alt=media&token=7a337b01-3825-4610-a7fa-7c75e82e0883',
      ],
    },
    {
      id: 6,
      title: '`Flamesoles.com` WordPress Site for USA Client in Upwork',
      summery:
        'This one is Woocomerce based on WordPress Ecommerce web site for the Shoes Selling . After Creating this, I complete It as a fully SEO website.',
      technologies: [''],
      usedModules: [''],
      live: 'https://flamesoles.com',
      source: '',
      image: mock2,
      imagesUrl: [
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/flamesole%20wordpress%2F1.png?alt=media&token=8b093bb5-3d3b-4053-8c5e-0eb72d3daa12',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/flamesole%20wordpress%2F2.png?alt=media&token=7313ec34-35ff-4276-bae5-a1ecd445754b',
        'https://firebasestorage.googleapis.com/v0/b/savindupasintha-71dd8.appspot.com/o/flamesole%20wordpress%2F3.png?alt=media&token=c115be18-bb96-422c-943f-c7811a4ce5b5',
      ],
    },
    {
      id: 4,
      title: 'QT GUI C++ Desktop Application(China)',
      summery:
        'This Project for the `Elastic Quality Checking Software Solution`',
      technologies: [
        'c++',
        'QT Framework',
        'IOT',
        'QML',
        'CSS',
        'Electric Motors',
        'Camera',
        'Lights',
      ],
      usedModules: [''],
      live: '',
      source: '',
      image: mock2,
      imagesUrl: [''],
    },
    {
      id: 6,
      title: 'React Js Portfolio Web Application',
      summery: 'A web site allow to view developer portfolio. ',
      technologies: [''],
      usedModules: [''],
      live: '',
      source: '',
      image: mock2,
      imagesUrl: [],
    },
    {
      id: 6,
      title: 'React Js Learning Web Application',
      summery:
        'A web site allow to find students to tuition classes and teachers can register web site.      ',
      technologies: [''],
      usedModules: [''],
      live: '',
      source: '',
      image: mock2,
      imagesUrl: [],
    },
    {
      id: 6,
      title: 'React Js Facemash web Application',
      summery:
        'A web site for when user click on the image s randomly image change .      ',
      technologies: [''],
      usedModules: [''],
      live: '',
      source: '',
      image: mock2,
      imagesUrl: [],
    },
    {
      id: 6,
      title: 'PHP Jewellery Full Ecommerce Web Application',
      summery:
        'A web site for full functional online jewellery selling. All the users can buy the jewellery item and Admin can manage stock.      ',
      technologies: [''],
      usedModules: [''],
      live: '',
      source:
        'https://github.com/savindu-pasintha/Java-EE-Hospital-Project-REST-Mysql-with-Jersey',
      image: mock2,
      imagesUrl: [],
    },
    {
      id: 6,
      title: 'Bakery Web Site',
      summery:
        'A web site for full functional online Bakery items selling. All the users can buy bakery items and Admin can manage stock',
      technologies: [''],
      usedModules: [''],
      live: '',
      source:
        'https://github.com/savindu-pasintha/Java-EE-Hospital-Project-REST-Mysql-with-Jersey',
      image: mock2,
      imagesUrl: [],
    },
    {
      id: 6,
      title: 'ASP.NET MVC  Web Application For `Hotel Booking System`',
      summery: 'A web site for Hotel Reservation .      ',
      technologies: [''],
      usedModules: [''],
      live: '',
      source:
        'https://github.com/savindu-pasintha/Java-EE-Hospital-Project-REST-Mysql-with-Jersey',
      image: mock2,
      imagesUrl: [],
    },
    {
      id: 6,
      title: ' ASP.NET MVC Web Application For `Flower Selling`',
      summery:
        'A web site for full functional flower selling and admin support to manage all the flower stocks and user accounts.',
      technologies: [''],
      usedModules: [''],
      live: '',
      source:
        'https://github.com/savindu-pasintha/Java-EE-Hospital-Project-REST-Mysql-with-Jersey',
      image: mock2,
      imagesUrl: [],
    },
    {
      id: 6,
      title: '`Hospital Management System` Java maven web application for ',
      summery:
        'This is java base web application . To develop this I used Java maven, Soap & Rest Service for complete my diploma program Technology as used Java Maven , JSP , Boostrap , Mysql databse',
      technologies: [''],
      usedModules: [''],
      live: '',
      source:
        'https://github.com/savindu-pasintha/Java-EE-Hospital-Project-REST-Mysql-with-Jersey',
      image: mock2,
      imagesUrl: [],
    },
    {
      id: 6,
      title: 'Pyhton Machine Learning System `Restaurant Rating Predict`',
      summery:
        'After the developing this system, I learnt all the necessary machine learning concept using python.To complete this project front end as rest service as a used `FLASK`` .',
      technologies: [''],
      usedModules: [''],
      live: '',
      source:
        'https://github.com/savindu-pasintha/Java-EE-Hospital-Project-REST-Mysql-with-Jersey',
      image: mock2,
      imagesUrl: [],
    },

    {
      id: 6,
      title: '` Book Store` Java Netbean DeskTop Application',
      summery:
        'A Desktop application for Store Book shop Book details. This application allows to Book Store manage with book searching functionalty',
      technologies: [''],
      usedModules: [''],
      live: '',
      source:
        'https://github.com/savindu-pasintha/Java-EE-Hospital-Project-REST-Mysql-with-Jersey',
      image: mock2,
      imagesUrl: [],
    },
    {
      id: 6,
      title: '`Whole sale Order Management System` ',
      summery:
        'A Desktop application for fully automation order management system.',
      technologies: [''],
      usedModules: [''],
      live: '',
      source:
        'https://github.com/savindu-pasintha/Java-EE-Hospital-Project-REST-Mysql-with-Jersey',
      image: mock2,
      imagesUrl: [],
    },
    {
      id: 6,
      title: '`Flower Management System ` C# Desktop Application',
      summery:
        'A Desktop application for fully automation flower selling and management system',
      technologies: [''],
      usedModules: [''],
      live: '',
      source:
        'https://github.com/savindu-pasintha/Java-EE-Hospital-Project-REST-Mysql-with-Jersey',
      image: mock2,
      imagesUrl: [],
    },
    {
      id: 6,
      title: 'C++ `Car Rental System`',
      summery:
        'A Desktop Console application for fully automation car rental management system.      ',
      technologies: [''],
      usedModules: [''],
      live: '',
      source:
        'https://github.com/savindu-pasintha/Java-EE-Hospital-Project-REST-Mysql-with-Jersey',
      image: mock2,
      imagesUrl: [],
    },
    {
      id: 6,
      title: 'Springboot Backend for `Hospital Management system`',
      summery: '',
      technologies: [''],
      usedModules: [''],
      live: '',
      source:
        'https://github.com/savindu-pasintha/Java-EE-Hospital-Project-REST-Mysql-with-Jersey',
      image: mock2,
      imagesUrl: [],
    },
    {
      id: 6,
      title: 'NodeJS/Express  Backend `',
      summery: '',
      technologies: [''],
      usedModules: [''],
      live: '',
      source:
        'https://github.com/savindu-pasintha/Java-EE-Hospital-Project-REST-Mysql-with-Jersey',
      image: mock2,
      imagesUrl: [],
    },
    {
      id: 6,
      title: '`Flutter App`',
      summery: '',
      technologies: [''],
      usedModules: [''],
      live: '',
      source:
        'https://github.com/savindu-pasintha/Java-EE-Hospital-Project-REST-Mysql-with-Jersey',
      image: mock2,
      imagesUrl: [],
    },

    {
      id: 6,
      title: '',
      summery: '',
      technologies: [''],
      usedModules: [''],
      live: '',
      source:
        'https://github.com/savindu-pasintha/Java-EE-Hospital-Project-REST-Mysql-with-Jersey',
      image: mock2,
      imagesUrl: [],
    },
  ],
}
